package com.github.ltsopensource.core.cmd;

/**
 * @author Robert HG (254963746@qq.com) on 3/11/16.
 */
public interface HttpCmdParamNames {

    String M_NODE = "mNode";

    String M_DATA = "mData";

    String PARAM_KEY_FOR_SUBMIT_OPERATION = "ltsTask";

    String PARAM_KEY_BASE_OPERATION_TASK_ID = "taskId";
    String PARAM_KEY_BASE_OPERATION_TASK_TRACKER_GROUP_NAME = "taskTrackerGroupName";

    String PARAM_KEY_FOR_KILL_OPERATION_TASK_ID = PARAM_KEY_BASE_OPERATION_TASK_ID;
    String PARAM_KEY_FOR_KILL_OPERATION_TASK_TRACKER_GROUP_NAME = PARAM_KEY_BASE_OPERATION_TASK_TRACKER_GROUP_NAME;
    String PARAM_KEY_FOR_SUSPEND_OPERATION_TASK_ID = PARAM_KEY_BASE_OPERATION_TASK_ID;
    String PARAM_KEY_FOR_SUSPEND_OPERATION_TASK_TRACKER_GROUP_NAME = PARAM_KEY_BASE_OPERATION_TASK_TRACKER_GROUP_NAME;
    String PARAM_KEY_FOR_RESUME_OPERATION_TASK_ID = PARAM_KEY_BASE_OPERATION_TASK_ID;
    String PARAM_KEY_FOR_RESUME_OPERATION_TASK_TRACKER_GROUP_NAME = PARAM_KEY_BASE_OPERATION_TASK_TRACKER_GROUP_NAME;

    String PARAM_KEY_FOR_RERUN_OPERATION_TASK_ID = PARAM_KEY_BASE_OPERATION_TASK_ID;
    String PARAM_KEY_FOR_RERUN_OPERATION_PLAN_TIME = "planTime";
}
